[build]
  publish = "/"
  command = ""

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[dev]
  port = 8000
  publish = "/"
  autoLaunch = false

[[headers]]
  for = "/*"
  [headers.values]
    X-UA-Compatible = "IE=edge"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
